name: Observatory Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Metadata
        run: |
          #!/bin/bash
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          SAN=$(( $(shuf -i 30-99 -n 1) ))  # 使用 shuf 生成随机数

          echo "当前时间：${DATE}"
          echo "SAN 值：${SAN}"

          # 替换 README.md 中的内容
          sed -i '/最后校准时间：/{s/最后校准时间：.*/最后校准时间：${DATE}/;n;s/警告：检测到.*/SAN-${SAN}\/99-critical/}' README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🌌 自动更新观测数据"
          branch: main
